name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0

    - name: install required packages
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y  build-essential libssl-dev libdb5.1-dev libdb5.1++-dev libboost-all-dev libqrencode-dev miniupnpc libminiupnpc-dev git ca-certificates 
      

    - name: make
      working-directory: src/
      run: make -f makefile.unix
